[[gemini-action-type]]
== {gemini} connector and action
++++
<titleabbrev>{gemini}</titleabbrev>
++++
:frontmatter-description: Add a connector that can send requests to {gemini}.
:frontmatter-tags-products: [kibana] 
:frontmatter-tags-content-type: [how-to] 
:frontmatter-tags-user-goals: [configure]


The {gemini} connector uses https://github.com/axios/axios[axios] to send a POST request to {gemini}. The connector uses the <<execute-connector-api,run connector API>> to send the request.

[float]
[[define-gemini-ui]]
=== Create connectors in {kib}

You can create connectors in *{stack-manage-app} > {connectors-ui}*.  

[float]
[[gemini-connector-configuration]]
==== Connector configuration

{gemini} connectors have the following configuration properties:

Name::      The name of the connector.
API URL::   The {gemini} request URL.
Default model:: The GAI model for {gemini} to use. Current support is for the Gemini models, defaulting to Gemini 1.5. The model can be set on a per request basis by including a "model" parameter alongside the request body.
OAuth Authentication::   OAuth based login for authentication.

[float]
[[gemini-action-configuration]]
=== Test connectors

You can test connectors with the <<execute-connector-api,run connector API>> or
as you're creating or editing the connector in {kib}.

The {gemini} actions have the following configuration properties.

Body::      A stringified JSON payload sent to the {gemini} Invoke Model API URL. For example:
+
[source,text]
--
{
  body: JSON.stringify({
  [
  {role: 'user',
    parts:[{
     text: 'Write the first line of a story about a magic backpack.'}]}
],
  {
  temperature: 0,
  maxOutputTokens: DEFAULT_TOKEN_LIMIT,
}
});
}
--
Model::      An optional string that will overwrite the connector's default model. For 

[float]
[[gemini-connector-networking-configuration]]
=== Connector networking configuration

Use the <<action-settings, Action configuration settings>> to customize connector networking configurations, such as proxies, certificates, or TLS settings. You can set configurations that apply to all your connectors or use `xpack.actions.customHostSettings` to set per-host configurations.
